---
title: "Parametric Reconciliation"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(kableExtra)
```

# Gaussian DGP 
```{r echo=FALSE}
DF_MultiV_Full_GausDGP <- read.csv("DF_MultiV_Full_GaussianDGP.csv")[,-1]


DF_MultiV_Full_GausDGP %>% 
  group_by(`F.method`, `R.method`, `Forecast.Horizon`) %>% 
  summarise(E.ES = round(mean(`Energy.score`), digits = 2), 
            E.VS = round(mean(`Variogram.score`), digits = 2)) -> DF_MultiV_Full_GausDGP



########################################
### Bottom level of the Hierarchy ###
########################################



DF_MultiV_Bot_GausDGP <- read.csv("DF_MultiV_Bot_GaussianDGP.csv")[,-1]


DF_MultiV_Bot_GausDGP %>% 
  group_by(`F.method`, `R.method`, `Forecast.Horizon`) %>% 
  summarise(E.LS = round(mean(`Log.score`), digits = 2)) -> DF_MultiV_Bot_GausDGP

DF_MultiV_Bot_GausDGP %>% 
  left_join(DF_MultiV_Full_GausDGP) %>% 
  ungroup() %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal")))-> DF_MultiV_GaussDGP
  


DF_MultiV_GaussDGP %>% 
  ungroup() %>% 
  gather(key = key, value = value, E.LS, E.ES, E.VS) %>% 
  unite(temp, Forecast.Horizon, key) %>% 
  spread(key = temp, value = value) %>% 
  dplyr::select(R.method, `1_E.LS`, `2_E.LS`, `3_E.LS`, 
         `1_E.ES`, `2_E.ES`, `3_E.ES`, 
         `1_E.VS`, `2_E.VS`, `3_E.VS`) %>% 
  rename("1" = `1_E.LS`, "2" = `2_E.LS`, "3" = `3_E.LS`, 
         "1" = `1_E.ES`, "2" = `2_E.ES`, "3" = `3_E.ES`, 
         "1" = `1_E.VS`, "2" = `2_E.VS`, "3" = `3_E.VS`)%>% 
   kable(format = "latex") %>% kable_styling("striped") %>% 
  kableExtra::add_header_above(c(" " = 1, "Log Score(%)" = 3, "Energy Score(%)" = 3, "Variogram Score(%)" = 3))

```

# Non Gaussian DGP

```{r echo=FALSE}
DF_MultiV_Full_NonGausDGP <- read.csv("DF_MultiV_Full_NonGaussianDGP.csv")[,-1]


DF_MultiV_Full_NonGausDGP %>% 
  group_by(`F.method`, `R.method`, `Forecast.Horizon`) %>% 
  summarise(E.ES = round(mean(`Energy.score`), digits = 2), 
            E.VS = round(mean(`Variogram.score`), digits = 2)) -> DF_MultiV_Full_NonGausDGP


########################################
### Bottom level of the Hierarchy ###
########################################



DF_MultiV_Bot_NonGausDGP <- read.csv("DF_MultiV_Bot_NonGaussianDGP.csv")[,-1]


DF_MultiV_Bot_NonGausDGP %>% 
  group_by(`F.method`, `R.method`, `Forecast.Horizon`) %>% 
  summarise(E.LS = round(mean(`Log.score`), digits = 2)) -> DF_MultiV_Bot_NonGausDGP

DF_MultiV_Bot_NonGausDGP %>% 
  left_join(DF_MultiV_Full_NonGausDGP) %>% 
  ungroup() %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal")))-> DF_MultiV_NonGausDGP
  


DF_MultiV_NonGausDGP %>% 
  ungroup() %>% 
  gather(key = key, value = value, E.LS, E.ES, E.VS) %>% 
  unite(temp, Forecast.Horizon, key) %>% 
  spread(key = temp, value = value) %>% 
  dplyr::select(R.method, `1_E.LS`, `2_E.LS`, `3_E.LS`, 
         `1_E.ES`, `2_E.ES`, `3_E.ES`, 
         `1_E.VS`, `2_E.VS`, `3_E.VS`) %>% 
  rename("1" = `1_E.LS`, "2" = `2_E.LS`, "3" = `3_E.LS`, 
         "1" = `1_E.ES`, "2" = `2_E.ES`, "3" = `3_E.ES`, 
         "1" = `1_E.VS`, "2" = `2_E.VS`, "3" = `3_E.VS`)%>% 
   kable(format = "latex") %>% kable_styling("striped") %>% 
  kableExtra::add_header_above(c(" " = 1, "Log Score(%)" = 3, "Energy Score(%)" = 3, "Variogram Score(%)" = 3))

```


# Comparing univariate predictive accuracy in aggregate levels
```{r echo=FALSE}
DF_UniV_GausDGP <- read.csv("DF_UniV_GaussianDGP.csv")[-1]

DF_UniV_GausDGP %>% 
  dplyr::select(-F.method) %>% 
  group_by(Series, R.method , `Forecast.Horizon`) %>% 
  summarise(E.CRPS = round(mean(CRPS), digits = 2), 
            E.LS = round(mean(LS), digits = 2)) -> DF_Mean_UnivScore_GausDGP

DF_Mean_UnivScore_GausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 1) %>% 
  dplyr::select(-Forecast.Horizon, -E.CRPS) %>% 
  spread(key = Series, value = E.LS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_LS_GausDGP_h1

DF_Mean_UnivScore_GausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 2) %>% 
  dplyr::select(-Forecast.Horizon, -E.CRPS) %>% 
  spread(key = Series, value = E.LS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_LS_GausDGP_h2

DF_Mean_UnivScore_GausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 3) %>% 
  dplyr::select(-Forecast.Horizon, -E.CRPS) %>% 
  spread(key = Series, value = E.LS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_LS_GausDGP_h3
  
DF_Mean_UnivScore_GausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 1) %>% 
  dplyr::select(-Forecast.Horizon, -E.LS) %>% 
  spread(key = Series, value = E.CRPS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_CRPS_GausDGP_h1

DF_Mean_UnivScore_GausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 2) %>% 
  dplyr::select(-Forecast.Horizon, -E.LS) %>% 
  spread(key = Series, value = E.CRPS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_CRPS_GausDGP_h2

DF_Mean_UnivScore_GausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 3) %>% 
  dplyr::select(-Forecast.Horizon, -E.LS) %>% 
  spread(key = Series, value = E.CRPS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_CRPS_GausDGP_h3
  


```




```{r echo=FALSE}
DF_UniV_NonGausDGP <- read.csv("DF_UniV_NonGaussianDGP.csv")[-1]

DF_UniV_NonGausDGP %>% 
  dplyr::select(-F.method) %>% 
  group_by(Series, R.method , `Forecast.Horizon`) %>% 
  summarise(E.CRPS = round(mean(CRPS), digits = 2), 
            E.LS = round(mean(LS), digits = 2)) -> DF_Mean_UnivScore_NonGausDGP

DF_Mean_UnivScore_NonGausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 1) %>% 
  dplyr::select(-Forecast.Horizon, -E.CRPS) %>% 
  spread(key = Series, value = E.LS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_LS_NonGausDGP_h1

DF_Mean_UnivScore_NonGausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 2) %>% 
  dplyr::select(-Forecast.Horizon, -E.CRPS) %>% 
  spread(key = Series, value = E.LS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_LS_NonGausDGP_h2

DF_Mean_UnivScore_NonGausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 3) %>% 
  dplyr::select(-Forecast.Horizon, -E.CRPS) %>% 
  spread(key = Series, value = E.LS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_LS_NonGausDGP_h3

DF_Mean_UnivScore_NonGausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 1) %>% 
  dplyr::select(-Forecast.Horizon, -E.LS) %>% 
  spread(key = Series, value = E.CRPS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_CRPS_NonGausDGP_h1

DF_Mean_UnivScore_NonGausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 2) %>% 
  dplyr::select(-Forecast.Horizon, -E.LS) %>% 
  spread(key = Series, value = E.CRPS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_CRPS_NonGausDGP_h2

DF_Mean_UnivScore_NonGausDGP %>% 
  ungroup() %>% 
  filter(Forecast.Horizon == 3) %>% 
  dplyr::select(-Forecast.Horizon, -E.LS) %>% 
  spread(key = Series, value = E.CRPS) %>% 
  dplyr::select(R.method, Total, A, B, V1, V2, V3, V4) %>% 
  rename("AA" = V1, "AB" = V2, "BA" = V3, "BB" = V4) %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal"))) -> DF_Mean_UnivScore_CRPS_NonGausDGP_h3


```

# For h=1

```{r echo=FALSE}
left_join(DF_Mean_UnivScore_LS_GausDGP_h1,
          DF_Mean_UnivScore_LS_NonGausDGP_h1, by = "R.method") %>% 
  mutate(R.method = factor(R.method, levels = c("Base", "Bottom up", "OLS", "WLS", "MinT.Sam", "MinT.Shr", "Optimal")))%>%
  as_tibble() %>% 
  kable(format = "latex") %>% kable_styling("striped") %>% 
  kableExtra::add_header_above(c(" " = 1, "Gaussian DGP" = 7, 
                                 "Non-Gaussian DGP" = 7))
  
left_join(DF_Mean_UnivScore_CRPS_GausDGP_h1,
          DF_Mean_UnivScore_CRPS_NonGausDGP_h1, by = "R.method") %>%
  as_tibble() %>% 
  kable(format = "latex") %>% kable_styling("striped") %>% 
  kableExtra::add_header_above(c(" " = 1, "Gaussian DGP" = 7, 
                                 "Non-Gaussian DGP" = 7))

```


# For h=2

```{r echo=FALSE}
left_join(DF_Mean_UnivScore_LS_GausDGP_h2,
          DF_Mean_UnivScore_LS_NonGausDGP_h2, by = "R.method") %>%
  as_tibble() %>% 
  kable(format = "latex") %>% kable_styling("striped") %>% 
  kableExtra::add_header_above(c(" " = 1, "Gaussian DGP" = 7, 
                                 "Non-Gaussian DGP" = 7))
  
left_join(DF_Mean_UnivScore_CRPS_GausDGP_h2,
          DF_Mean_UnivScore_CRPS_NonGausDGP_h2, by = "R.method") %>%
  as_tibble() %>% 
  kable(format = "latex") %>% kable_styling("striped") %>% 
  kableExtra::add_header_above(c(" " = 1, "Gaussian DGP" = 7, 
                                 "Non-Gaussian DGP" = 7))

```

# For h=3

```{r echo=FALSE}
left_join(DF_Mean_UnivScore_LS_GausDGP_h3,
          DF_Mean_UnivScore_LS_NonGausDGP_h3, by = "R.method") %>%
  as_tibble() %>% 
  kable(format = "latex") %>% kable_styling("striped") %>% 
  kableExtra::add_header_above(c(" " = 1, "Gaussian DGP" = 7, 
                                 "Non-Gaussian DGP" = 7))
  
left_join(DF_Mean_UnivScore_CRPS_GausDGP_h3,
          DF_Mean_UnivScore_CRPS_NonGausDGP_h3, by = "R.method") %>%
  as_tibble() %>% 
  kable(format = "latex") %>% kable_styling("striped") %>% 
  kableExtra::add_header_above(c(" " = 1, "Gaussian DGP" = 7, 
                                 "Non-Gaussian DGP" = 7))

```


